apiVersion: 1

datasources:
  - name: FPL Postgres
    uid: fpl-postgres
    type: postgres
    access: proxy
    url: ${POSTGRES_HOST}:${POSTGRES_PORT}
    database: ${POSTGRES_DB}
    user: ${POSTGRES_USER}
    isDefault: true
    secureJsonData:
      password: ${POSTGRES_PASSWORD}
    jsonData:
      sslmode: ${POSTGRES_SSLMODE}
      postgresVersion: 1600
      maxOpenConns: 5
