-- Every table is scoped by `season` (e.g. '2025-26') so historical seasons and
-- the current live season can coexist. `player_code` is FPL's stable player
-- identifier across seasons; `player_id`/element ids are only stable within a
-- single season, so cross-season joins should go through `player_code`.

CREATE TABLE IF NOT EXISTS teams (
    season TEXT NOT NULL,
    id INT NOT NULL,
    code INT,
    name TEXT NOT NULL,
    short_name TEXT NOT NULL,
    strength_overall_home INT,
    strength_overall_away INT,
    strength_attack_home INT,
    strength_attack_away INT,
    strength_defence_home INT,
    strength_defence_away INT,
    PRIMARY KEY (season, id)
);

ALTER TABLE teams ADD COLUMN IF NOT EXISTS code INT;

CREATE TABLE IF NOT EXISTS players (
    season TEXT NOT NULL,
    id INT NOT NULL,
    code INT NOT NULL,
    first_name TEXT,
    second_name TEXT,
    web_name TEXT NOT NULL,
    team_id INT NOT NULL,
    element_type INT NOT NULL,
    now_cost INT NOT NULL,
    status TEXT,
    news TEXT,
    chance_of_playing_next_round INT,
    PRIMARY KEY (season, id),
    FOREIGN KEY (season, team_id) REFERENCES teams (season, id)
);

ALTER TABLE players ADD COLUMN IF NOT EXISTS status TEXT;
ALTER TABLE players ADD COLUMN IF NOT EXISTS news TEXT;
ALTER TABLE players ADD COLUMN IF NOT EXISTS chance_of_playing_next_round INT;

CREATE TABLE IF NOT EXISTS gameweeks (
    season TEXT NOT NULL,
    id INT NOT NULL,
    name TEXT NOT NULL,
    deadline_time TIMESTAMPTZ,
    finished BOOLEAN NOT NULL DEFAULT FALSE,
    is_current BOOLEAN NOT NULL DEFAULT FALSE,
    is_next BOOLEAN NOT NULL DEFAULT FALSE,
    average_entry_score INT,
    highest_score INT,
    PRIMARY KEY (season, id)
);

CREATE TABLE IF NOT EXISTS fixtures (
    season TEXT NOT NULL,
    id INT NOT NULL,
    gameweek INT,
    team_h INT NOT NULL,
    team_a INT NOT NULL,
    team_h_score INT,
    team_a_score INT,
    kickoff_time TIMESTAMPTZ,
    finished BOOLEAN NOT NULL DEFAULT FALSE,
    team_h_difficulty INT,
    team_a_difficulty INT,
    PRIMARY KEY (season, id),
    FOREIGN KEY (season, team_h) REFERENCES teams (season, id),
    FOREIGN KEY (season, team_a) REFERENCES teams (season, id)
);

ALTER TABLE fixtures ADD COLUMN IF NOT EXISTS team_h_difficulty INT;
ALTER TABLE fixtures ADD COLUMN IF NOT EXISTS team_a_difficulty INT;

-- One row per player per gameweek: the core historical fact table the AI
-- advisor reasons over.
CREATE TABLE IF NOT EXISTS player_gameweek_stats (
    season TEXT NOT NULL,
    player_code INT NOT NULL,
    player_id INT NOT NULL,
    gameweek INT NOT NULL,
    fixture_id INT,
    team_id INT,
    opponent_team_id INT,
    was_home BOOLEAN,
    minutes INT NOT NULL DEFAULT 0,
    goals_scored INT NOT NULL DEFAULT 0,
    assists INT NOT NULL DEFAULT 0,
    clean_sheets INT NOT NULL DEFAULT 0,
    goals_conceded INT NOT NULL DEFAULT 0,
    own_goals INT NOT NULL DEFAULT 0,
    penalties_saved INT NOT NULL DEFAULT 0,
    penalties_missed INT NOT NULL DEFAULT 0,
    yellow_cards INT NOT NULL DEFAULT 0,
    red_cards INT NOT NULL DEFAULT 0,
    saves INT NOT NULL DEFAULT 0,
    bonus INT NOT NULL DEFAULT 0,
    bps INT NOT NULL DEFAULT 0,
    influence NUMERIC,
    creativity NUMERIC,
    threat NUMERIC,
    ict_index NUMERIC,
    total_points INT NOT NULL DEFAULT 0,
    value INT,
    selected INT,
    transfers_in INT,
    transfers_out INT,
    PRIMARY KEY (season, player_code, gameweek)
);

CREATE TABLE IF NOT EXISTS managers (
    team_id INT PRIMARY KEY,
    name TEXT,
    player_first_name TEXT,
    player_last_name TEXT
);

CREATE TABLE IF NOT EXISTS manager_gameweek_history (
    team_id INT NOT NULL REFERENCES managers (team_id),
    season TEXT NOT NULL,
    gameweek INT NOT NULL,
    points INT,
    total_points INT,
    overall_rank INT,
    bank INT,
    team_value INT,
    event_transfers INT,
    event_transfers_cost INT,
    points_on_bench INT,
    PRIMARY KEY (team_id, season, gameweek)
);

CREATE TABLE IF NOT EXISTS manager_picks (
    team_id INT NOT NULL REFERENCES managers (team_id),
    season TEXT NOT NULL,
    gameweek INT NOT NULL,
    player_id INT NOT NULL,
    player_code INT,
    squad_position INT,
    multiplier INT NOT NULL DEFAULT 1,
    is_captain BOOLEAN NOT NULL DEFAULT FALSE,
    is_vice_captain BOOLEAN NOT NULL DEFAULT FALSE,
    PRIMARY KEY (team_id, season, gameweek, player_id)
);

-- Latest AI advisor output for the upcoming gameweek, generated by a
-- scheduled job (not the frontend) and read verbatim by the web app.
CREATE TABLE IF NOT EXISTS advisor_suggestions (
    team_id INT NOT NULL REFERENCES managers (team_id),
    season TEXT NOT NULL,
    for_gameweek INT NOT NULL,
    free_transfers INT NOT NULL,
    suggestion JSONB NOT NULL,
    generated_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    PRIMARY KEY (team_id, season, for_gameweek)
);

-- Every classic/h2h league the manager belongs to, with their own current
-- and previous rank in it (from the FPL entry endpoint).
CREATE TABLE IF NOT EXISTS manager_leagues (
    team_id INT NOT NULL REFERENCES managers (team_id),
    season TEXT NOT NULL,
    league_id INT NOT NULL,
    league_name TEXT NOT NULL,
    league_type TEXT NOT NULL,
    entry_rank INT,
    entry_last_rank INT,
    PRIMARY KEY (team_id, season, league_id)
);

-- Standings snapshot (top pages only) for classic leagues. Head-to-head
-- leagues aren't populated here (different scoring model) — they still
-- appear in manager_leagues, just without a standings table.
CREATE TABLE IF NOT EXISTS league_standings (
    season TEXT NOT NULL,
    league_id INT NOT NULL,
    entry_team_id INT NOT NULL,
    entry_name TEXT,
    player_name TEXT,
    rank INT,
    last_rank INT,
    total INT,
    event_total INT,
    PRIMARY KEY (season, league_id, entry_team_id)
);

-- Public read-only access for the frontend (Supabase anon key). The ingest
-- job connects as the table owner, which bypasses RLS, so this only
-- restricts anonymous/frontend access, never the pipeline itself. Only
-- applies on Supabase, which provisions the `anon` role; local Docker
-- Postgres has no such role and isn't exposed publicly, so this is a no-op
-- there.
DO $$
DECLARE
    t TEXT;
BEGIN
    IF EXISTS (SELECT 1 FROM pg_roles WHERE rolname = 'anon') THEN
        FOR t IN SELECT unnest(ARRAY['teams', 'players', 'gameweeks', 'fixtures',
            'player_gameweek_stats', 'managers', 'manager_gameweek_history', 'manager_picks',
            'advisor_suggestions', 'manager_leagues', 'league_standings'])
        LOOP
            EXECUTE format('ALTER TABLE %I ENABLE ROW LEVEL SECURITY', t);
            EXECUTE format('DROP POLICY IF EXISTS public_read ON %I', t);
            EXECUTE format('CREATE POLICY public_read ON %I FOR SELECT TO anon USING (true)', t);
        END LOOP;
    END IF;
END $$;

-- Read-only aggregate views for the web frontend. Views execute with the
-- owner's privileges (security_invoker defaults to off), so they read the
-- underlying tables regardless of RLS; the frontend just needs SELECT on the
-- view itself. Season-scoped season totals per player, one row per
-- (season, player_code), including last-5-GW form and current ownership.
CREATE OR REPLACE VIEW v_player_season AS
SELECT
    p.season,
    p.code                          AS player_code,
    p.id                            AS player_id,
    p.web_name,
    p.element_type,
    p.now_cost,
    p.status,
    p.news,
    p.chance_of_playing_next_round,
    t.id                            AS team_id,
    t.short_name                    AS team_short_name,
    t.code                          AS team_code,
    COALESCE(agg.games_played, 0)   AS games_played,
    COALESCE(agg.total_points, 0)   AS total_points,
    COALESCE(agg.goals_scored, 0)   AS goals_scored,
    COALESCE(agg.assists, 0)        AS assists,
    COALESCE(agg.clean_sheets, 0)   AS clean_sheets,
    COALESCE(agg.minutes, 0)        AS minutes,
    COALESCE(agg.bonus, 0)          AS bonus,
    COALESCE(agg.bps, 0)            AS bps,
    COALESCE(agg.ict_index, 0)      AS ict_index,
    CASE WHEN COALESCE(agg.games_played, 0) > 0
         THEN ROUND(agg.total_points::numeric / agg.games_played, 2)
         ELSE 0 END                 AS points_per_game,
    CASE WHEN p.now_cost > 0
         THEN ROUND(COALESCE(agg.total_points, 0)::numeric / (p.now_cost / 10.0), 2)
         ELSE 0 END                 AS points_per_million,
    own.selected                    AS ownership,
    COALESCE(f5.form_5, 0)          AS form_5,
    COALESCE(f5.form_series, ARRAY[]::int[]) AS form_series
FROM players p
JOIN teams t ON t.season = p.season AND t.id = p.team_id
LEFT JOIN LATERAL (
    SELECT
        COUNT(*) FILTER (WHERE s.minutes > 0) AS games_played,
        SUM(s.total_points)                   AS total_points,
        SUM(s.goals_scored)                   AS goals_scored,
        SUM(s.assists)                        AS assists,
        SUM(s.clean_sheets)                   AS clean_sheets,
        SUM(s.minutes)                        AS minutes,
        SUM(s.bonus)                          AS bonus,
        SUM(s.bps)                            AS bps,
        ROUND(AVG(s.ict_index), 1)            AS ict_index
    FROM player_gameweek_stats s
    WHERE s.season = p.season AND s.player_code = p.code
) agg ON TRUE
LEFT JOIN LATERAL (
    SELECT
        SUM(x.total_points)                              AS form_5,
        array_agg(x.total_points ORDER BY x.gameweek)    AS form_series
    FROM (
        SELECT s.total_points, s.gameweek
        FROM player_gameweek_stats s
        WHERE s.season = p.season AND s.player_code = p.code
        ORDER BY s.gameweek DESC
        LIMIT 5
    ) x
) f5 ON TRUE
LEFT JOIN LATERAL (
    SELECT s.selected
    FROM player_gameweek_stats s
    WHERE s.season = p.season AND s.player_code = p.code
    ORDER BY s.gameweek DESC
    LIMIT 1
) own ON TRUE;

DO $$
BEGIN
    IF EXISTS (SELECT 1 FROM pg_roles WHERE rolname = 'anon') THEN
        EXECUTE 'GRANT SELECT ON v_player_season TO anon';
    END IF;
END $$;
